worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  sendfile on;
  keepalive_timeout 65;

  # 현재 활성 라우팅 설정 1개만 로드 (blue/green 전환 시 current.conf 교체)
  include /etc/nginx/conf.d/current.conf;
}
