spring:
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: "${MAIL_USERNAME}" # SMTP 서버 로그인 아이디: 발신자
    password: "${MAIL_PASSWORD}" # SMTP 서버 로그인 패스워드
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부
          timeout: 5000 # Socket Read Timeout 시간(ms)
          starttls:
            enable: true # StartTLS 활성화 여부
  application:
    name: back
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
      # 대규모 트래픽 병목을 해소하기 위해 커넥션 풀 최대 크기를 10(기본값)에서 50으로 증가
      maximum-pool-size: 50

  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        # 연관 데이터를 100개씩 한 번에 IN 쿼리로 가져옴
#        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 10MB      # 파일 하나당 최대 크기
      max-request-size: 10MB   # 요청 전체 최대 크기
  cloud:
    aws:
      credentials:
        access-key: "${AWS_ACCESS_KEY}"
        secret-key: "${AWS_SECRET_KEY}"
      s3:
        bucket: "${AWS_BUCKET_NAME}"
      region:
        static: "ap-northeast-2"

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.orm.jdbc.extract: TRACE
#    org.springframework.transaction.interceptor: TRACE
    com.back: INFO
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      enabled: true

custom:
  jwt:
    secretKey: "${JWT_SECRET_KEY}"
  accessToken:
    expirationSeconds: "#{60*20}"
google:
  gemini:
    api-key: "${GEMINI_API_KEY}"