upstream backend_active {
  server backend-blue:8080;
}

server {
  listen 80;
  server_name _;

  location /api/ {
    proxy_pass http://backend_active;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    default_type text/plain;
    return 200 "NBE8-10-3-Team04 API server is running.\n";
  }
}
